main: main.c matrix.c
	gcc -g main.c matrix.c

# matrix: matrix_zip
		
# matrix_copy: matrix.h-master/matrix.c matrix.h-master/matrix.h
# 	cp "matrix.h-master/matrix.c" .
# 	cp "matrix.h-master/matrix.h" .

# matrix_unzip: master.zip
# 	unzip master.zip

# matrix_zip:
# 	curl -LOk https://github.com/iwatakeshi/matrix.h/archive/master.zip

clean:
	rm -f master.zip
	rm -r -f matrix.h-master